# Site settings
title: Guru Ram Daas Trust - Kundalini Yoga in Birmingham and the Midlands
email: info@grdtrust.org
description: "Guru Ram Daas Trust - Kundalini Yoga (as taught by Yogi Bhajan) in Birmingham and the Midlands"
baseurl: "/"
# url: "http://www.grdtrust.org"

# Build settings
markdown: kramdown
permalink: pretty
